### ISSUE TITLE
unfamiliar characters after name of Lojban word in search

### ISSUE THREAD

**Issue by refola** [La-Lojban/sutysisku#11]
## Reproduction

1. Search for something (e.g., [`broda`](https://la-lojban.github.io/sutysisku/en/#seskari=cnano&sisku=broda)).
2. Look to the right of any Lojban word in the search result.

## Expected result

This English-Lojban search should only have content in … English and Lojban.

## Actual result

I see unfamiliar glyphs encoded in the Unicode Private Use Area. For example, after `broda` is ``, which is a string of the following codepoints `U+ED90`, `U+ED94`, `U+EDA3`, `U+ED91`, `U+EDA0`.

## Additional information

The `<h4>` element has `class="valsi zlm"`. Online search results say that "ZLM" is a Malay language code, but the unfamiliar symbols don't look anything like search results for Malay scripts.

## System information

Browsers: Firefox and Chrome
OS: Chakra Linux
Fonts: I have Dotsies, Quikscript, and jsMath fonts installed, but the unfamiliar characters look like something else

**Comment by lagleki** [comment]
A link to zbalermorna added to the front page of English sutysisku, zlm css
class renamed to zbalermorna

**Comment by refola** [comment]
{.ki'e .ui} I can confirm that it's now adequately explained in [commit 9e87443e5cf28d0ed351622df7b155a2701b4eb4](https://github.com/La-Lojban/sutysisku/commit/9e87443e5cf28d0ed351622df7b155a2701b4eb4) and its parent commits.

(By the way, it would be useful for browsing to use more {.e'o .a'o} descriptive commit messages than `commit`.…)
