### ISSUE TITLE
Cannot decompose lujvo

### ISSUE THREAD

**Issue by player-03** [La-Lojban/sutysisku#12]
When searching for lujvo, la sutysisku rarely finds useful information.

Examples:

- If you search for [sutysisku](https://la-lojban.github.io/sutysisku/jb/#seskari=cnano&sisku=sutysisku), it breaks it into the expected pieces (sut + sisku), but it only recognizes "sisku".
- If you search for [jbobau](https://la-lojban.github.io/sutysisku/jb/#seskari=cnano&sisku=jbobau), it breaks it up into a single piece (bau), which it doesn't recognize.
- If you search for [fu'ivla](https://la-lojban.github.io/sutysisku/jb/#seskari=cnano&sisku=fu%27ivla), it breaks it up into a single piece (fu'i), which it doesn't recognize.
- If you search for [selbri](https://la-lojban.github.io/sutysisku/jb/#seskari=cnano&sisku=selbri), it breaks it up into a single piece (sel), which it doesn't recognize. But at least in this case there's an entry specifically for "selbrivla" that provides the definition.

I think this means your database of rafsi got corrupted or deleted. For any gismu, the only known rafsi are (1) that gismu and (2) that gismu with the final letter replaced with "y". Not the actual rafsi.

Take the entry for "[bangu](https://la-lojban.github.io/sutysisku/jb/#seskari=cnano&sisku=bangu)". At the bottom it says "rafsi: bangu bangy", and nowhere in there does it list "ban" or "bau". This seems to explain why when you search for "jbobau" it can't figure out what "bau" means.

**Comment by lagleki** [comment]
Please use English sutysisku instead of Dictionary with Examples

**Comment by player-03** [comment]
Huh, I didn't even notice the language in the URL. The English version works much better. Thanks!

**Comment by player-03** [comment]
For anyone else who runs into this issue (probably because you're using Clozemaster), what you want to do is change the language in the url from "jb" to "en". Or change it to "jbo" if you want a lojban definition.

Actually, an easier option is to click "la sutysisku" at the top. You'll see flags representing different languages, and when you click one, it'll translate the word you just searched into that language.
