### ISSUE TITLE
Links to CLL sections are broken

### ISSUE THREAD

**Issue by ltrel** [La-Lojban/sutysisku#21]
The links to sections of the CLL that can be found when searching sutysisku no longer work and show a 404 error page.
![image](https://user-images.githubusercontent.com/79512656/150759968-cc40f36c-30e9-4d14-a4dc-a90ab1199a37.png)
![image](https://user-images.githubusercontent.com/79512656/150760006-b2f0362d-b253-474d-a39e-8b597724d21b.png)

**Comment by ltrel** [comment]
Fixed, presumably by 1ee2d5a628d47cad8c22e4484c7f490eaf850c3b

**Comment by lagleki** [comment]
fixed via https://github.com/lagleki/livla/commit/5b1818e5d2dd260d4e3e46bbd602a8fb36f13624
