### ISSUE TITLE
'lu is not defined' exception

### ISSUE THREAD

**Issue by Pendrokar** [La-Lojban/sutysisku#9]
Throws an exception without noticeable notification when entering:

_.i la .lojban. na kulnu selkai steci_ - second line from the list [https://mw.lojban.org/index.php?title=Lojban&setlang=jbo](https://mw.lojban.org/index.php?title=Lojban&setlang=jbo)

**Comment by lagleki** [comment]
English version must be fixed now.

ki'e sai do noi sidju

**Comment by Pendrokar** [comment]
Confirming fix.
